<?php

namespace Adeliom\EasySeoBundle\Services;

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class BreadCrumbCollection
{
    /**
     * @var array
     */
    protected $items = [];

    /**
     * @var UrlGeneratorInterface $generator
     */
    protected $generator;

    /**
     * Adds new simple breadcrumb item. Leave target empty to create a breadcrumb item without a link.
     * @param string $linkName
     * @param string|null $target
     * @return void
     */
    public function addSimpleItem(string $linkName, string $target = null): void
    {
        $this->items[] = ["linkName" => $linkName, "target" => $target];
    }

    /**
     * Adds new breadcrumb item where target is being generated by the url generator
     * @param string $linkName
     * @param array $route
     * @return void
     */
    public function addRouteItem(string $linkName, array $route): void
    {
        $url = isset($route['params']) ? $this->generator->generate($route['route'], $route['params']) :
            $this->generator->generate($route['route']);

        $this->addSimpleItem($linkName, $url);
    }

    /**
     * Return all BreadCrumbs
     * @return array
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * @param UrlGeneratorInterface $generator
     * @return void
     */
    public function setGenerator(UrlGeneratorInterface $generator): void
    {
        $this->generator = $generator;
    }
}
