<?php

namespace Adeliom\EasySeoBundle\Services;

use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class BreadcrumbCollection
{
    /**
     * @var array
     */
    protected $items = [];

    /**
     * @var UrlGeneratorInterface
     */
    protected $generator;

    /**
     * Adds new simple breadcrumb item. Leave target empty to create a breadcrumb item without a link.
     */
    public function addSimpleItem(string $linkName, string $target = null): void
    {
        $this->items[] = ['linkName' => $linkName, 'target' => $target];
    }

    /**
     * Adds new breadcrumb item where target is being generated by the url generator.
     */
    public function addRouteItem(string $linkName, array $route): void
    {
        $url = isset($route['params']) ? $this->generator->generate($route['route'], $route['params']) :
            $this->generator->generate($route['route']);

        $this->addSimpleItem($linkName, $url);
    }

    /**
     * Return all Breadcrumbs.
     */
    public function getItems(): array
    {
        return $this->items;
    }

    public function setGenerator(UrlGeneratorInterface $generator): void
    {
        $this->generator = $generator;
    }
}
