services:
  Adeliom\EasySeoBundle\Twig\EasySeoExtension:
    arguments:
      - "@twig"
      - "@event_dispatcher"
      - "@easy_seo.breadcrumb"
      - '%easy_seo.title%'
      - '%easy_seo.breadcrumbs%'
    tags:
      - twig.extension

  easy_seo.breadcrumb:
    class: Adeliom\EasySeoBundle\Services\BreadcrumbCollection
    public: true
    calls:
      - [ 'setGenerator', [ '@router.default' ] ]

  Adeliom\EasySeoBundle\Services\BreadcrumbCollection:
    alias: easy_seo.breadcrumb

  Adeliom\EasySeoBundle\Form\SeoType:
    public: true

  Adeliom\EasySeoBundle\DataCollector\SeoCollector:
    arguments:
      - '@easy_seo.breadcrumb'
      - '%easy_seo.title%'
      - '%easy_seo.enable_profiler%'
      - '%easy_seo.ignore_profiler%'
    tags:
      - name: data_collector
        template: '@EasySeo/profiler/collector.html.twig'
        id: Adeliom\EasySeoBundle\DataCollector\SeoCollector
